# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rapport.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowRapport(object):
    def setupUi(self, MainWindowRapport):
        MainWindowRapport.setObjectName("MainWindowRapport")
        MainWindowRapport.resize(609, 620)
        MainWindowRapport.setStyleSheet("background-color: rgb(85, 85, 127)")
        self.centralwidget = QtWidgets.QWidget(MainWindowRapport)
        self.centralwidget.setObjectName("centralwidget")
        self.list_Purchas = QtWidgets.QListWidget(self.centralwidget)
        self.list_Purchas.setGeometry(QtCore.QRect(20, 320, 561, 221))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_Purchas.setFont(font)
        self.list_Purchas.setStyleSheet("border: 3px Solid rgb(48, 252, 255);\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px")
        self.list_Purchas.setObjectName("list_Purchas")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.Client = QtWidgets.QLineEdit(self.centralwidget)
        self.Client.setGeometry(QtCore.QRect(110, 100, 321, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Client.setFont(font)
        self.Client.setStyleSheet("\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px Solid rgb(48, 252, 255);\n"
"border-radius: 18px;\n"
" ")
        self.Client.setText("")
        self.Client.setPlaceholderText("")
        self.Client.setObjectName("Client")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 271, 51))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Product = QtWidgets.QLineEdit(self.centralwidget)
        self.Product.setGeometry(QtCore.QRect(110, 190, 321, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Product.setFont(font)
        self.Product.setStyleSheet("\n"
"\n"
"background-color: rgb(255, 255, 255);\n"
"border: 3px Solid rgb(48, 252, 255);\n"
"border-radius: 18px;\n"
" ")
        self.Product.setText("")
        self.Product.setPlaceholderText("")
        self.Product.setObjectName("Product")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 260, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(450, 100, 141, 161))
        self.Search_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Search_btn.setFont(font)
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("#Search_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(60, 255, 39);\n"
"border: 3px Solid rgb(1, 134, 1);\n"
"\n"
"}\n"
"#Search_btn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.Search_btn.setObjectName("Search_btn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 0, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(27)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        MainWindowRapport.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowRapport)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 29))
        self.menubar.setObjectName("menubar")
        MainWindowRapport.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowRapport)
        self.statusbar.setObjectName("statusbar")
        MainWindowRapport.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowRapport)
        QtCore.QMetaObject.connectSlotsByName(MainWindowRapport)

    def retranslateUi(self, MainWindowRapport):
        _translate = QtCore.QCoreApplication.translate
        MainWindowRapport.setWindowTitle(_translate("MainWindowRapport", "MainWindow"))
        self.label_3.setText(_translate("MainWindowRapport", "Client :"))
        self.label_4.setText(_translate("MainWindowRapport", "Produt :"))
        self.label.setText(_translate("MainWindowRapport", "List of  Purchasing :"))
        self.Search_btn.setText(_translate("MainWindowRapport", "Search "))
        self.label_5.setText(_translate("MainWindowRapport", "Rapport Screen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowRapport = QtWidgets.QMainWindow()
    ui = Ui_MainWindowRapport()
    ui.setupUi(MainWindowRapport)
    MainWindowRapport.show()
    sys.exit(app.exec_())
